stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    - data/external/tweet_emotions.csv
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  model_building:
    cmd: python src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    - model_building.max_depth
    outs:
    - models
  model_evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/model.pkl
    - src/models/evaluate_model.py
    metrics:
    - metrics.json